Allow use of external configMap for NGINX configuration
zalf-rdm/geonode-k8s pull request #113
Opened 2023-11-08 17:42 UTC by AlexGacon

## Description

A brief description of the feature or bug that this pull request addresses.

## Type of Change

Please select the relevant option:

- [ ] Bug fix
- [ ] New feature
- [ ] Documentation update
- [ ] Refactoring
- [ ] Other (please describe)

## Related Issue

If there is an existing issue related to this pull request, please reference it here.

closes #112

## Checklist

Please ensure that your pull request meets the following requirements:

- The pull request is limited to one type (docs, feature, bug fix, etc.)
- The pull request is as small as possible. Consider opening multiple pull requests instead of one large one.
- The feature or bug fix has been discussed and documented in an issue beforehand.

## Additional Notes

Any additional information or context regarding the pull request can be provided here.

Thank you for creating this pull request

2023-11-10 09:31 UTC, mwallschlaeger commented on charts/geonode/templates/nginx/nginx-deploy.yaml
would be nice to add the optional configmap to the annotations if existingConfigMapName variable is defined. This would allow automatic restart of the container if the configuration changes

2023-11-10 10:42 UTC, AlexGacon commented on charts/geonode/templates/nginx/nginx-deploy.yaml
Good suggestions indeed

2023-11-10 10:59 UTC, AlexGacon commented on charts/geonode/templates/nginx/nginx-deploy.yaml
I had a quick look and it seems difficult to do without using a non-standard operator (see https://renehernandez.io/notes/rolling-pods-config-changes/)

2023-11-10 11:07 UTC, mwallschlaeger commented on charts/geonode/templates/nginx/nginx-deploy.yaml
ah yes I understand the issue. Would it be an alternative to define the overwrite nginx configuration itself as a value in the values.yaml and overload the content of the nignx-conf.yaml file?

2023-11-10 13:15 UTC, AlexGacon commented on charts/geonode/templates/nginx/nginx-deploy.yaml
Could be a good option too, I will work on it.

2023-11-11 10:26 UTC, AlexGacon commented on charts/geonode/templates/nginx/nginx-deploy.yaml
The option of having the overwritten nginx configuration in the values.yaml prevents from using helm functions to tweak the configuration based on other elements of the global configuration.

2023-11-11 10:39 UTC, AlexGacon commented on charts/geonode/templates/nginx/nginx-deploy.yaml
What I really need is to be activate CORS for an external domain for integration purpose. So another option si to add optional Access-Control-Allow-Origin directive into the configuration and to allow to define a target domain into the configuration. What do you think of this?

2023-11-13 09:50 UTC, mwallschlaeger commented on charts/geonode/templates/nginx/nginx-deploy.yaml
@AlexGacon  If its only about the CORS, I would suggest to add values only to modify this point in nginx.conf. As I looked into the nginx configuration a bit more it might be possible to reduce the size of the configuration by removing the parts for geoserver and pycsw in a later version and use direct ingress configuration for them. For now I'm ether okay with just changing CORS attributes or making it possible to add an external configmap, even without reloading via the annotations. Just write me if I should have another look. I would merge both PRs than

2023-11-14 05:11 UTC, AlexGacon commented on charts/geonode/templates/nginx/nginx-deploy.yaml
@mwallschlaeger I just pushed the changes on my fork.

2023-11-14 07:59 UTC, mwallschlaeger requested changes
the branch has a conflict with the main branch. please update your branch. Than I can approve this PR

2023-11-14 10:29 UTC, AlexGacon commented
Rebase done and pushed

2023-11-14 14:19 UTC, mwallschlaeger approved these changes

2023-11-14 14:19 UTC, merged