Add geoserver printing host customiization
zalf-rdm/geonode-k8s pull request #225
Opened 2024-11-26 08:43 UTC by AlexGacon

## Description

This PR completes the configuration of the printing service of GeoServer to works with the URL of GeoNode and adds the possibility to define additional hosts in the values.yaml file.

## Type of Change

Please select the relevant option:

- [ ] Bug fix
- [x] New feature
- [ ] Documentation update
- [ ] Refactoring
- [ ] Other (please describe)

## Related Issue

If there is an existing issue related to this pull request, please reference it here.

closes #223 

## Checklist

Please ensure that your pull request meets the following requirements:

- The pull request is limited to one type (docs, feature, bug fix, etc.)
- The pull request is as small as possible. Consider opening multiple pull requests instead of one large one.
- The feature or bug fix has been discussed and documented in an issue beforehand.

## Additional Notes

Any additional information or context regarding the pull request can be provided here.

Thank you for creating this pull request

2024-11-26 08:50 UTC, mwallschlaeger requested changes
@AlexGacon for me its very unclear where all the configuration inside of the `charts/geonode/templates/geoserver/geoserver-printing-config-yaml.yaml` files comes from. Are this default values from the GeoServer or did you gather them by yourself?

#edit: ok after reading the related issue I fully overview the problem. Maybe you could at least add a header to the yaml file describing where the content is comming from and that its served or controlled by geonode-k8s helm chart. So people manually straving inside the geoserver container will know what they are looking at.

2024-11-26 08:50 UTC, mwallschlaeger commented on charts/geonode/templates/geoserver/geoserver-printing-config-yaml.yaml
> +    # brokenUrlPlaceholder: 'throw'
please remove commented code

2024-11-26 08:50 UTC, mwallschlaeger commented on charts/geonode/templates/geoserver/geoserver-printing-config-yaml.yaml
> +    #proxyBaseUrl: http://geoserver:8080/geoserver/pdf
please remove commented code

2024-11-26 08:50 UTC, mwallschlaeger commented on charts/geonode/templates/geoserver/geoserver-printing-config-yaml.yaml
> +    #===========================================================================
could you add some documentation here where this list is coming from?

2024-11-26 09:40 UTC, AlexGacon commented on charts/geonode/templates/geoserver/geoserver-printing-config-yaml.yaml
> +    # brokenUrlPlaceholder: 'throw'
Done

2024-11-26 09:40 UTC, AlexGacon commented on charts/geonode/templates/geoserver/geoserver-printing-config-yaml.yaml
> +    #proxyBaseUrl: http://geoserver:8080/geoserver/pdf
Done

2024-11-26 09:41 UTC, AlexGacon commented on charts/geonode/templates/geoserver/geoserver-printing-config-yaml.yaml
> +    #===========================================================================
Documentation added and I have moved the custom part at the end of the list, with additional comments.

2024-11-26 09:41 UTC, AlexGacon commented
@mwallschlaeger is the removal of notifier.xml ok for you?

2024-11-27 06:43 UTC, mwallschlaeger commented
@AlexGacon yes removing of the xml is fine, as its served via geoserver docker image

2024-11-27 06:43 UTC, mwallschlaeger approved these changes
Looks fine to me now in total.

2024-11-27 06:43 UTC, merged