Issue#27 py csw single microservice
zalf-rdm/geonode-k8s pull request #34
Opened 2023-07-31 10:03 UTC by mwallschlaeger

Closes #27 

## 📑 Description
ref #27

added pycsw microservice inspired by pycsw helm chart (https://github.com/geopython/pycsw/tree/master/docker/helm) with adoption to the style of this helm chart.

Implementation:
- nginx container forwarding traffic to pycsw via  `.Values.pycsw.endpoint` url
- mappings.py taken from GeoNode codbase (https://github.com/GeoNode/geonode/blob/master/geonode/catalogue/backends/pycsw_local_mappings.py)
- pycsw.cfg taken from pycsw helm chart

## ℹ Additional Information

2023-08-03 11:03 UTC, mwallschlaeger commented
waiting for https://github.com/GeoNode/geonode/pull/11319 . meanwhile you can use the following geonode image including the bugfix promoted inside the PR.
```
  image:
    # -- used geonode image
    name: mwall2bitflow/geonode
    # -- tag of used geonode image
    tag: '4.1.x-pycsw-hotfix'
```

2023-08-23 12:25 UTC, mwallschlaeger commented
https://github.com/GeoNode/geonode/pull/11319 got merged, so no reason to hold this back anymore

2023-09-04 11:44 UTC, ridoo requested changes

2023-09-04 11:44 UTC, ridoo commented on deployment/geonode/templates/_helpers.tpl
> +{{ .Release.Name }}-{{ .Values.pycsw.pod_name }}
https://github.com/zalf-rdm/geonode-k8s/issues/64

2023-09-04 11:44 UTC, ridoo commented on deployment/geonode/templates/geonode/geonode-env.yaml
> +  CATALOGUE_URL: "http://{{ include "pycsw_pod_name" . }}:{{ .Values.pycsw.port }}"
https://github.com/zalf-rdm/geonode-k8s/issues/64

2023-09-04 11:44 UTC, ridoo commented on deployment/geonode/templates/nginx/nginx-conf.yaml
> +        proxy_pass http://{{ include "pycsw_pod_name" . }}:{{ .Values.pycsw.port }};
#64

2023-09-04 11:44 UTC, ridoo commented on deployment/geonode/templates/pycsw/pycsw-cfg.yaml
> +  pycsw.cfg: |+
Should we better include that configuration as is in the values.yml and embed the config via `{{- include "pycsw.config" . | nindent 4 }}`?

2023-09-04 11:44 UTC, ridoo commented on deployment/geonode/templates/pycsw/pycsw-deploy.yaml
> +  name: "{{ include "pycsw_pod_name" . }}"
#64

2023-09-04 11:44 UTC, ridoo commented on deployment/geonode/templates/pycsw/pycsw-env.yaml
> +  name: {{ include "pycsw_pod_name" . }}-env
#64

2023-09-04 11:44 UTC, ridoo commented on deployment/geonode/templates/pycsw/pycsw-svc.yaml
> +  name: "{{ include "pycsw_pod_name" . }}"
#64

2023-09-04 11:44 UTC, ridoo commented on docs/pycsw.md
> +GeoNode-k8s external pycsw container. This allows changes to pyCSW with having to change GeoNode codebase and allows scalability of the pyCSW service seperatly. The external pycsw service is by defau
_without_ having to change GeoNode

2023-09-04 11:44 UTC, ridoo commented on docs/pycsw.md
> +The csw endpoint is default set to the one used within Geonode: `/catalogue/csw`
Would be nice to have a link reference here, e.g. https://docs.pycsw.org/en/2.6.1/configuration.html

2023-09-04 11:44 UTC, ridoo commented on minikube-values.yaml
> +  enabled: True
Really the default?

2023-09-04 11:45 UTC, ridoo requested changes
We do not have to resolve #64 first, but at least should have a look at the way how the config is embedded in the configMap

2023-09-05 06:07 UTC, mwallschlaeger commented on deployment/geonode/templates/pycsw/pycsw-deploy.yaml
> +  name: "{{ include "pycsw_pod_name" . }}"
lets work on #64 in another PR

2023-09-05 06:07 UTC, mwallschlaeger commented on deployment/geonode/templates/nginx/nginx-conf.yaml
> +        proxy_pass http://{{ include "pycsw_pod_name" . }}:{{ .Values.pycsw.port }};
lets work on #64 in another PR

2023-09-05 06:07 UTC, mwallschlaeger commented on deployment/geonode/templates/geonode/geonode-env.yaml
> +  CATALOGUE_URL: "http://{{ include "pycsw_pod_name" . }}:{{ .Values.pycsw.port }}"
lets work on #64 in another PR

2023-09-05 06:07 UTC, mwallschlaeger commented on deployment/geonode/templates/_helpers.tpl
> +{{ .Release.Name }}-{{ .Values.pycsw.pod_name }}
lets work on #64 in another PR

2023-09-05 06:09 UTC, mwallschlaeger commented on deployment/geonode/templates/pycsw/pycsw-env.yaml
> +  name: {{ include "pycsw_pod_name" . }}-env
lets work on #64 in another PR

2023-09-06 08:23 UTC, closed without merging