Issue#49 add a configurable fixture template
zalf-rdm/geonode-k8s pull request #50
Opened 2023-08-08 12:39 UTC by ridoo

Closes #49

2023-08-08 12:40 UTC, ridoo commented on deployment/geonode/templates/_helpers.tpl
> +{{- if or ( not .Values.geonode.ingress.externalPort ) (eq (toString .Values.geonode.ingress.externalPort) "80") (eq (toString .Values.geonode.ingress.externalPort) "443") -}}
Urgh .. this should not be part of this PR .. I will remove this

2023-08-08 12:57 UTC, mwallschlaeger commented on deployment/geonode/values.yaml
> +favicon: AAABAAMAEBAAAAEAIABoBAAANgAAACAgAAABACAAKBEAAJ4EAAAwMAAAAQAgAGgmAADGFQAAKAAAABAAAAAgAAAAAQAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACoqKhIpKSlQPDcuj2tTOM9NQDLsVEY0qyoqKmUnJycgJycnICoqKmVMXF2rRlNV7F
should this be something like:
```
favicon: |
```

2023-08-09 07:03 UTC, mwallschlaeger requested changes
As the values.yaml has changed please add documentation for the added parameters and run the doc generating tool https://github.com/norwoodj/helm-docs/releases/v1.11.0

2023-08-09 09:42 UTC, mwallschlaeger approved these changes

2023-08-09 09:43 UTC, merged

2023-08-09 11:58 UTC, ridoo commented on deployment/geonode/templates/geonode/geonode-env.yaml
> +  FIXTURE_DIRS: "[ '/usr/src/geonode/fixtures' ]"
@mwallschlaeger This does not match the actually configured volume:

https://github.com/zalf-rdm/geonode-k8s/pull/50/files#diff-fca9f77d2a6cb907ee65a0f6252b1261757188e043aed583e778fccdc9b1d4baR131

I will have to provide a quick fix for that