WIP: Provide confidential values as secret
zalf-rdm/geonode-k8s pull request #71
Opened 2023-09-06 15:40 UTC by ridoo

## Description

Separates confidential values (currently the superuser credentials) from `values.yaml` into a Kubernetes Secret. 
Provides a `templates/demo-secret.yaml` by default. However, can be overridden by a custom secret which can be referenced by name in the `values.yaml`.

@mwallschlaeger please have a look, if you think this is a path we may want to follow. If you are ok, I will continue refactoring the remaining credentials.

## Type of Change

Please select the relevant option:

- [ ] Bug fix
- [x] New feature
- [x] Documentation update
- [ ] Refactoring
- [ ] Other (please describe)

## Related Issue

If there is an existing issue related to this pull request, please reference it here.

closes #

## Checklist

Please ensure that your pull request meets the following requirements:

- The pull request is limited to one type (docs, feature, bug fix, etc.)
- The pull request is as small as possible. Consider opening multiple pull requests instead of one large one.
- The feature or bug fix has been discussed and documented in an issue beforehand.

## Additional Notes

Any additional information or context regarding the pull request can be provided here.

Thank you for creating this pull request

2023-09-07 06:38 UTC, mwallschlaeger commented on charts/geonode/values.yaml
I agree on storing sensitive data in secrets makes sense. But I don't understand why you want to deploy them  separately. In my opinion this makes the deployment more complex. Could we keep the definition inside the values.yaml but store them in kubernetes secrets? Generally securing sensitive data in the values.yaml on the deployment server  should be part of the CI tool, like argocd or flux. Those tools provide mechanisms to secure secrets in values.yaml like `sops` or `vault`.

2023-09-08 08:02 UTC, mwallschlaeger requested changes
see my two remarks on this. else i'm fine with the general idea on this now.

2023-09-08 08:02 UTC, mwallschlaeger commented on charts/geonode/templates/geonode/geonode-deploy.yaml
> +            name: {{ .Values.geoserver.secret.existingSecretName | "geoserver-secret" | quote }}
This isn't working. Error in linting here. You could do init variable at top of file and ref variable like: 
```
{{- $geoserver_secret := .Values.geoserver.secret.existingSecretName | default "geoserver-secret" | quote }}
{{- $geonode_secret := .Values.geonode.secret.existingSecretName | default "geonode-secret" | quote }}
```
and include like:
```
          - secretRef:
              name: {{ $geoserver_secret }} # watch idention here https://stackoverflow.com/questions/53518245/how-to-pass-all-values-from-multiple-secrets-to-env-variables-in-kubernetes
          - secretRef:
              name: {{ $geonode_secret }}
```

2023-09-08 08:02 UTC, mwallschlaeger commented on charts/geonode/templates/geonode/geonode-secret.yaml
> +  ADMIN_EMAIL: {{ .Values.geonode.secret.content.superUser.email | b64enc }}
`content` does not exist remove it from values

2023-09-08 08:07 UTC, mwallschlaeger commented on charts/geonode/templates/geoserver/geoserver-deploy.yaml
> +              name: {{ .Values.geoserver.secret.existingSecretName | "geoserver-secret" | quote }}
See comments on geonode-deploy.yaml herefor

2023-09-08 08:43 UTC, mwallschlaeger approved these changes

2023-09-08 15:08 UTC, ridoo commented on charts/geonode/templates/geonode/geonode-deploy.yaml
> +            name: {{ .Values.geoserver.secret.existingSecretName | "geoserver-secret" | quote }}
Yes, I saw it already and provided a solutions using `default`

2023-09-08 15:08 UTC, ridoo commented on charts/geonode/templates/geonode/geonode-secret.yaml
> +  ADMIN_EMAIL: {{ .Values.geonode.secret.content.superUser.email | b64enc }}
fixed it

2023-09-08 15:11 UTC, ridoo commented on charts/geonode/templates/postgres/postgres-external-geonode-secrets.yaml
> +{{ if and ( .Values.postgres.external_postgres.enabled (empty .Values.postgres.external_postgres.secret.existingSecretName )) }}
This does not work -- will provide a fix and unblock

2023-09-08 15:33 UTC, ridoo commented on charts/geonode/templates/postgres/postgres-external-geonode-secrets.yaml
> +{{ if and ( .Values.postgres.external_postgres.enabled (empty .Values.postgres.external_postgres.secret.existingSecretName )) }}
https://repeatit.io/ FTW

2023-09-08 16:00 UTC, mwallschlaeger requested changes

2023-09-08 16:00 UTC, mwallschlaeger commented on docs/provide-custom-secret.md
> +
this isn't up-to-date with the latest changes to this pull request anymore

2023-09-10 08:06 UTC, mwallschlaeger approved these changes

2023-09-10 08:06 UTC, merged