release 1.0.0 final changes [geonode 4.1.2]
zalf-rdm/geonode-k8s pull request #74
Opened 2023-09-08 09:23 UTC by mwallschlaeger

## Description

This PR fixes minor issues with the chart and prepares for the new chart release 1.0.0. 
* ref #72 #73 
* update docs
* pycsw microservice is disabled by default, as its missing some changes to geonode which will be released with version 4.2 (https://github.com/GeoNode/geonode/pull/11319)
* now using 52north/geonode:4.1.2 image, as long as official images are not ready (https://github.com/GeoNode/geonode-project/issues/471), geonode-k8s will get a new minor release as soon as the new images are there

## Type of Change

Please select the relevant option:

- [x] Bug fix
- [ ] New feature
- [x] Documentation update
- [ ] Refactoring
- [ ] Other (please describe)

## Related Issue

If there is an existing issue related to this pull request, please reference it here.

closes #72 #73 

## Checklist

Please ensure that your pull request meets the following requirements:

- The pull request is limited to one type (docs, feature, bug fix, etc.)
- The pull request is as small as possible. Consider opening multiple pull requests instead of one large one.
- The feature or bug fix has been discussed and documented in an issue beforehand.

## Additional Notes

Any additional information or context regarding the pull request can be provided here.

Thank you for creating this pull request

2023-09-08 13:50 UTC, ridoo requested changes
What about the secret separation? Do you plan to include this in another release?

2023-09-08 13:50 UTC, ridoo commented on charts/geonode/README.md
> +| pycsw | object | `{"config":"[server]\n    home=/home/pycsw\n    url=$(PYCSW_SERVER_URL)\n    mimetype=application/xml; charset=UTF-8\n    encoding=UTF-8\n    language= en-US\n    maxrecords=10\n
I would not bloat the README so much. In doubt, just [remove documentation](https://github.com/zalf-rdm/geonode-k8s/blob/4c688f745491cbb8db1a154a5bb2a1c85be18ebf/charts/geonode/values.yaml#L371) for the whole `pycsw` part.

2023-09-08 13:50 UTC, ridoo commented on charts/geonode/README.md
> +| pycsw.mappings | string | `"MD_CORE_MODEL = {\n  \"typename\": \"pycsw:CoreMetadata\",\n  \"outputschema\": \"http://pycsw.org/metadata\",\n  \"mappings\": {\n      \"pycsw:Identifier\": \"uuid\",\
As above: Use `# -- @ignore` or (perhaps better) [`# -- @default <something>`](https://github.com/zalf-rdm/geonode-k8s/blob/4c688f745491cbb8db1a154a5bb2a1c85be18ebf/charts/geonode/values.yaml#L401) flag  here

2023-09-08 16:13 UTC, mwallschlaeger commented
> What about the secret separation? Do you plan to include this in another release?

no i want to wait until the secret separation is merged and add it to the release.

2023-09-11 09:05 UTC, ridoo approved these changes
Looks good

2023-09-11 10:20 UTC, merged